wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.30
      8:
      - 5
batch_size:
  desc: null
  value: 32
data_dir:
  desc: null
  value: /data_plus/dataset/my_fgvc_dataset/letterbox/
device:
  desc: null
  value: 0,5
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.02
model_size:
  desc: null
  value: 101
momentum:
  desc: null
  value: 0.937
num_class:
  desc: null
  value: 3
save_dir:
  desc: null
  value: result/
use_pretrained:
  desc: null
  value: false
